### ISSUE TITLE
Can't inject DLLs into a 64 bit process

### ISSUE THREAD

**Issue by charliea21** [HubbyteDev/SharpNeedle#1]
I cant inject my DLL into a 64 bit process, here's the exception thrown:

```text
System.ComponentModel.Win32Exception: 'A 32 bit processes cannot access modules of a 64 bit process.'
```

**Comment by ashleyww93** [comment]
Hey.

Thanks for trying to use SharpNeedle. You need to compile the project at x64, this should fix your issue.

I hope this helps, feel free to let me know what your using this for and I'll add it to the read me as an example.

**Comment by charliea21** [comment]
Okay!
